import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import { AppProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoLaos = Noto_Sans_Lao({
  variable: "--font-noto-lao",
  subsets: ["lao"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Learn NextJS Beginner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="lo">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoLaos.variable} antialiased bg-gray-50 font-[family-name:var(--font-noto-lao)] transition-colors duration-300 dark:bg-gray-950`}
      >
        <AppProvider>
          <div className="flex min-h-screen">
            {/* Sidebar */}
            <Sidebar />

            {/* Main Content */}
            <div className="flex-1 flex flex-col">
              <Header />
              <main className="p-8 flex-1">
                <div className="max-w-7xl mx-auto">{children}</div>
              </main>
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
